# Site settings
title: Agostinho Soto-wang
email: asotowang@ucsd.edu
url: https://github.com/AgostinhoSotowWang.github.io
description: "I am a bioengineering student at UC San Diego with a focus in bioinformatics, intent on applying ML and deep learning models for driving both research and translational decisions. I have experience in quantitative microscopy and epigenomic analysis. My experience and passion lies in understanding the tumor microenvironment. In the Mechantransduction in Immune Network lab at UC San Diego and Moores Cancer Center, I have contributed to single cell time series analysis."
keywords: "Machine Learning, Deep Learning, Oncology, Immunotherapy"
skills: "Computational Biologist -- Data Scientist -- UCSD Student"
meta_author: Soto-wang Agostinho

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Agostinho Soto-wang
  location: La Jolla, CA
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/agostinho-s-w/
  - title: github
    url: https://github.com/AgostinhoS?tab=repositories

# Postal address (add as many lines as necessary)
address:
  - line: xxxx xxxxxxxxxx xxx
  - line: La Mesa, CA 91941

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
